keyconfig_version = (4, 0, 36)
keyconfig_data = \
[("Dopesheet",
  {"space_type": 'DOPESHEET_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("column", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("column", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True, "oskey": True},
     {"properties":
      [("channel", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("channel", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True, "oskey": True},
     {"properties":
      [("extend", True),
       ("channel", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ("channel", True),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "oskey": True},
     {"properties":
      [("mode", 'CHECK'),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "oskey": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", True),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", True),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'LEFT'),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'RIGHT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("axis_range", False),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'B', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis_range", True),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("mode", 'SET'),
       ("tweak", True),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ("tweak", True),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "oskey": True},
     {"properties":
      [("mode", 'SUB'),
       ("tweak", True),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ("tweak", True),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "oskey": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "oskey": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("action.select_circle",
     {"type": 'C', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("mode", 'KEYS'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "oskey": True},
     {"properties":
      [("mode", 'CFRA'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'CFRA'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MARKERS_COLUMN'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MARKERS_BETWEEN'),
       ],
      },
     ),
    ("action.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("action.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("action.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("action.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("action.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("action.frame_jump", {"type": 'G', "value": 'PRESS', "oskey": True}, None),
    ("action.frame_jump", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'DOPESHEET_MT_snap_pie'),
       ],
      },
     ),
    ("action.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("action.handle_type", {"type": 'V', "value": 'PRESS'}, None),
    ("action.interpolation_type", {"type": 'T', "value": 'PRESS'}, None),
    ("action.extrapolation_type", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("action.easing_type", {"type": 'E', "value": 'PRESS', "oskey": True}, None),
    ("action.easing_type", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("action.keyframe_type", {"type": 'R', "value": 'PRESS'}, None),
    ("action.bake_keys", {"type": 'O', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_delete'),
       ],
      },
     ),
    ("action.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("confirm", False),
       ],
      },
     ),
    ("action.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("action.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("action.copy", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("action.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("action.paste", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("action.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("action.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ("action.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ("action.previewrange_set", {"type": 'P', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("action.previewrange_set", {"type": 'P', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("action.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("action.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("action.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("action.view_frame", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_view_pie'),
       ],
      },
     ),
    ("anim.channels_editable_toggle", {"type": 'TAB', "value": 'PRESS'}, None),
    ("anim.channels_select_filter", {"type": 'F', "value": 'PRESS', "oskey": True}, None),
    ("anim.channels_select_filter", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("transform.transform",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_TRANSLATE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("mode", 'TIME_TRANSLATE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_EXTEND'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_SCALE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'TIME_SLIDE'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_action'),
       ],
      },
     ),
    ("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("marker.camera_bind", {"type": 'B', "value": 'PRESS', "oskey": True}, None),
    ("marker.camera_bind", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_context_menu'),
       ],
      },
     ),
    ("anim.change_frame", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
